<?php

/**
 * @file
 * helfi_strategia.module
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function helfi_strategia_theme(): array {
  return [
    'hyte_search' => [
      'variables' => [
        'search_element' => NULL,
        'description' => NULL,
      ],
      'template' => 'hyte-search',
    ],
    'hyte_search_hero_block' => [
      'variables' => [
        'hero_title' => NULL,
        'first_paragraph_bg' => NULL,
      ],
      'template' => 'hyte-search-hero-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function helfi_strategia_preprocess_html(&$variables): void {
  $route = \Drupal::routeMatch()->getRouteName();

  // Set the theme color to suomenlinna on Helsinki near you landing pages.
  $hyte_search = [
    'helfi_strategia.hyte_search',
  ];

  if (in_array($route, $hyte_search)) {
    $variables['theme_color'] = 'copper';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_strategia_preprocess_page(&$variables): void {
  $route = \Drupal::routeMatch()->getRouteName();

  // There is hero block on Hyte search page but
  // since it isn't a paragraph we must set this variable manually.
  if ($route === 'helfi_strategia.hyte_search') {
    $variables['has_hero'] = TRUE;
  }
}
