_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'system.site:page.front'
  - 'hdbt_admin_tools.site_settings:site_settings'
  - 'hdbt_admin_tools.site_settings:footer_settings'
  - 'easy_breadcrumb.settings:home_segment_title'
  - block.block.ibmchatapp
  - block.block.ibmchatapp_neuvonta_fi
  - block.block.ibmchatapp_neuvonta_sv
  - block.block.ibmchatapp_neuvonta_en
  - block.block.ibmchatapp_watson_talpa
