<?php
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_entity_form_display_alter().
 */
function helfi_ahjo_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  if ($context['entity_type'] == 'taxonomy_term' && $context['form_mode'] == 'default') {
    $form_display
      ->setComponent('field_external_id', [
        'region' => 'content',
      ])
      ->setComponent('field_external_parent_id', [
        'region' => 'content',
      ])
      ->setComponent('field_section_type', [
        'region' => 'content',
      ])
      ->setComponent('field_section_type_id', [
        'region' => 'content',
      ])
      ->setComponent('field_o_position', [
        'region' => 'content',
      ]);
  }
}

/**
 * Implements hook_form_alter().
 */
function helfi_ahjo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form['#form_id'] == 'taxonomy_term_sote_section_form') {
    $form['field_external_id']['widget'][0]['#type'] = 'textfield';
    $form['field_external_parent_id']['widget'][0]['#type'] = 'textfield';
    $form['field_section_type']['widget'][0]['#type'] = 'textfield';
    $form['field_section_type_id']['widget'][0]['#type'] = 'textfield';
  }

}

/**
 * Implements hook_theme().
 */
function helfi_ahjo_theme($existing, $type, $theme, $path) {
  return [
    'hierarchical_taxonomy_tree' => [
      'variables' => [
        'menu_tree' => [],
        'route_tid' => NULL,
        'vocabulary' => NULL,
        'current_depth' => 0,
        'max_depth' => 0,
        'collapsible' => NULL,
      ],
    ],
    'organigram_container' => [
      'variables' => [
        'menu_tree' => [],
      ],
    ],
  ];

}

/**
 * Implements hook_cron().
 */
function helfi_ahjo_cron() {
  $config = \Drupal::configFactory()->get('helfi_ahjo.config');
  /** @var int $last_run */
  $last_run = \Drupal::state()->get('helfi_ahjo.last_run', 0);
  /** @var int $request_time */
  $request_time = \Drupal::time()->getRequestTime();
  $interval = $config->get('sync_interval') ?? 3600;

  // Check if we need to execute.
  if ($interval !== -1 && $last_run + $interval >= $request_time) {
    return;
  }

  $count = \Drupal::queue('sote_section_update')->numberOfItems();

  if ($count > 0) {
    $logger = \Drupal::service('logger.factory')->get('helfi_ahjo');
    $logger->info('Cron execution has been cancelled because the queue @queue_name is not empty (@count items)..', [
      '@count' => $count,
      '@queue_name' => 'Acquia DAM Asset Refresh',
    ]);
    return;
  }

  $jsonFile = Json::decode(\Drupal::service('helfi_ahjo.ahjo_service')->fetchDataFromRemote());
  $queue = \Drupal::queue('sote_section_update');
  \Drupal::service('helfi_ahjo.ahjo_service')->addToCron($jsonFile, $queue);

  $count = \Drupal::queue('sote_section_update')->numberOfItems();

  /** @var \Drupal\Core\Logger\LoggerChannelInterface $logger */
  $logger = \Drupal::service('logger.factory')->get('helfi_ahjo');
  $logger->info('Total items in the queue: @count.', ['@count' => $count]);
  \Drupal::service('helfi_ahjo.ahjo_service')->syncTaxonomyTermsTree();
  \Drupal::state()->set('helfi_ahjo.last_run', $request_time);
}
